<% project_name = 'compounding-log-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: compounding_log_api_development

test:
  <<: *default
  database: compounding_log_api_test
